name: vhs
on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - vhs.tape
jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install timg and vhs
        run: brew install timg vhs
      - name: Run tape
        run: vhs vhs.tape
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'
